CREATE TABLE [cerner].[CODE_VALUE] (
    [CODE_VALUE]             FLOAT (53)    NOT NULL,
    [CODE_SET]               FLOAT (53)    NULL,
    [CDF_MEANING]            VARCHAR (12)  NULL,
    [DISPLAY]                VARCHAR (40)  NULL,
    [DISPLAY_KEY]            VARCHAR (40)  NULL,
    [DESCRIPTION]            VARCHAR (60)  NULL,
    [DEFINITION]             VARCHAR (100) NULL,
    [COLLATION_SEQ]          FLOAT (53)    NULL,
    [ACTIVE_TYPE_CD]         FLOAT (53)    NULL,
    [UPDT_CNT]               FLOAT (53)    NULL,
    [ACTIVE_DT_TM]           DATETIME      NULL,
    [INACTIVE_DT_TM]         DATETIME      NULL,
    [UPDT_DT_TM]             DATETIME      NULL,
    [UPDT_ID]                FLOAT (53)    NULL,
    [UPDT_TASK]              FLOAT (53)    NULL,
    [UPDT_APPLCTX]           FLOAT (53)    NULL,
    [ACTIVE_IND]             FLOAT (53)    NULL,
    [BEGIN_EFFECTIVE_DT_TM]  DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID] FLOAT (53)    NULL,
    [END_EFFECTIVE_DT_TM]    DATETIME      NULL,
    [DATA_STATUS_CD]         FLOAT (53)    NULL,
    [DATA_STATUS_DT_TM]      DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]   FLOAT (53)    NULL,
    [CKI]                    VARCHAR (255) NULL,
    [DISPLAY_KEY_NLS]        VARCHAR (255) NULL,
    [CONCEPT_CKI]            VARCHAR (255) NULL,
    [DISPLAY_KEY_A_NLS]      VARCHAR (160) NULL,
    [LAST_UTC_TS]            VARCHAR (75)  NULL,
    [CLU_SUBKEY1_FLAG]       FLOAT (53)    NULL,
    [INST_ID]                FLOAT (53)    NULL,
    [RowCreated]             DATETIME2 (3) NOT NULL,
    [RowModified]            DATETIME2 (3) NULL,
    [RowDeleted]             DATETIME2 (0) NULL,
    [RowAltered]             DATETIME2 (0) NOT NULL, 
    CONSTRAINT [PK_CODE_VALUE] PRIMARY KEY ([CODE_VALUE])
);

