CREATE TABLE [cerner].[PERSON_NAME]
(
	[PERSON_NAME_ID] [numeric](38, 4) NOT NULL,
	[PERSON_ID] [numeric](38, 4) NULL,
	[NAME_TYPE_CD] [numeric](38, 4) NULL,
	[UPDT_CNT] [numeric](38, 4) NULL,
	[UPDT_DT_TM] [datetime] NULL,
	[UPDT_ID] [numeric](38, 4) NULL,
	[UPDT_TASK] [numeric](38, 4) NULL,
	[UPDT_APPLCTX] [numeric](38, 4) NULL,
	[ACTIVE_IND] [numeric](38, 4) NULL,
	[ACTIVE_STATUS_CD] [numeric](38, 4) NULL,
	[ACTIVE_STATUS_DT_TM] [datetime] NULL,
	[ACTIVE_STATUS_PRSNL_ID] [numeric](38, 4) NULL,
	[BEG_EFFECTIVE_DT_TM] [datetime] NULL,
	[END_EFFECTIVE_DT_TM] [datetime] NULL,
	[NAME_ORIGINAL] [varchar](100) NULL,
	[NAME_FORMAT_CD] [numeric](38, 4) NULL,
	[NAME_FULL] [varchar](100) NULL,
	[NAME_FIRST] [varchar](100) NULL,
	[NAME_MIDDLE] [varchar](100) NULL,
	[NAME_LAST] [varchar](100) NULL,
	[NAME_DEGREE] [varchar](100) NULL,
	[NAME_TITLE] [varchar](100) NULL,
	[NAME_PREFIX] [varchar](100) NULL,
	[NAME_SUFFIX] [varchar](100) NULL,
	[NAME_INITIALS] [varchar](100) NULL,
	[DATA_STATUS_CD] [numeric](38, 4) NULL,
	[DATA_STATUS_DT_TM] [datetime] NULL,
	[DATA_STATUS_PRSNL_ID] [numeric](38, 4) NULL,
	[CONTRIBUTOR_SYSTEM_CD] [numeric](38, 4) NULL,
	[NAME_FIRST_KEY] [varchar](100) NULL,
	[NAME_LAST_KEY] [varchar](100) NULL,
	[NAME_MIDDLE_KEY] [varchar](100) NULL,
	[NAME_FIRST_KEY_NLS] [varchar](202) NULL,
	[NAME_LAST_KEY_NLS] [varchar](202) NULL,
	[NAME_MIDDLE_KEY_NLS] [varchar](202) NULL,
	[SOURCE_IDENTIFIER] [varchar](255) NULL,
	[NAME_TYPE_SEQ] [numeric](38, 4) NULL,
	[NAME_FIRST_KEY_A_NLS] [varchar](400) NULL,
	[NAME_LAST_KEY_A_NLS] [varchar](400) NULL,
	[NAME_MIDDLE_KEY_A_NLS] [varchar](400) NULL,
	[LAST_UTC_TS] [datetime] NULL,
	[INST_ID] [numeric](38, 4) NULL
	, RowCreated DATETIME2(3) NOT NULL
	, RowModified DATETIME2(3) NULL
	, RowDeleted DATETIME2(0) NULL
	, RowAltered DATETIME2(0) NOT NULL, 
    CONSTRAINT [PK_PERSON_NAME] PRIMARY KEY ([PERSON_NAME_ID]), 
)
