CREATE TABLE [cerner].[PERSON_ORG_RELTN] (
    [PERSON_ORG_RELTN_ID]    FLOAT (53)    NOT NULL,
    [PERSON_ID]              FLOAT (53)    NULL,
    [PERSON_ORG_RELTN_CD]    FLOAT (53)    NULL,
    [ORGANIZATION_ID]        FLOAT (53)    NULL,
    [UPDT_CNT]               FLOAT (53)    NULL,
    [UPDT_DT_TM]             DATETIME      NULL,
    [UPDT_ID]                FLOAT (53)    NULL,
    [UPDT_TASK]              FLOAT (53)    NULL,
    [UPDT_APPLCTX]           FLOAT (53)    NULL,
    [ACTIVE_IND]             FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]       FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]    DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID] FLOAT (53)    NULL,
    [BEG_EFFECTIVE_DT_TM]    DATETIME      NULL,
    [END_EFFECTIVE_DT_TM]    DATETIME      NULL,
    [DATA_STATUS_CD]         FLOAT (53)    NULL,
    [SOURCE_IDENTIFIER]      VARCHAR (255) NULL,
    [DATA_STATUS_DT_TM]      DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]   FLOAT (53)    NULL,
    [PERSON_ORG_NBR]         VARCHAR (100) NULL,
    [PERSON_ORG_ALIAS]       VARCHAR (100) NULL,
    [EMPL_TYPE_CD]           FLOAT (53)    NULL,
    [EMPL_STATUS_CD]         FLOAT (53)    NULL,
    [EMPL_OCCUPATION_TEXT]   VARCHAR (100) NULL,
    [EMPL_OCCUPATION_CD]     FLOAT (53)    NULL,
    [EMPL_TITLE]             VARCHAR (100) NULL,
    [EMPL_POSITION]          VARCHAR (100) NULL,
    [EMPL_CONTACT]           VARCHAR (100) NULL,
    [EMPL_CONTACT_TITLE]     VARCHAR (100) NULL,
    [FREE_TEXT_IND]          FLOAT (53)    NULL,
    [FT_ORG_NAME]            VARCHAR (100) NULL,
    [PRIORITY_SEQ]           FLOAT (53)    NULL,
    [INTERNAL_SEQ]           FLOAT (53)    NULL,
    [EMPL_RETIRE_DT_TM]      DATETIME      NULL,
    [EMPL_HIRE_DT_TM]        DATETIME      NULL,
    [EMPL_TERM_DT_TM]        DATETIME      NULL,
    [CONTRIBUTOR_SYSTEM_CD]  FLOAT (53)    NULL,
    [LAST_UTC_TS]            VARCHAR (75)  NULL,
    [EMPL_TITLE_CD]          FLOAT (53)    NULL,
    [INST_ID]                FLOAT (53)    NULL,
    [RowCreated]             DATETIME2 (3) NOT NULL,
    [RowModified]            DATETIME2 (3) NULL,
    [RowDeleted]             DATETIME2 (0) NULL,
    [RowAltered]             DATETIME2 (0) NOT NULL, 
    CONSTRAINT [PK_PERSON_ORG_RELTN] PRIMARY KEY ([PERSON_ORG_RELTN_ID])
);

