CREATE TABLE [cerner].[ENCNTR_PROCEDURE] (
    [ENCNTR_PROCEDURE_ID]          FLOAT (53)    NOT NULL,
    [CATALOG_CD]                   FLOAT (53)    NULL,
    [SYNONYM_ID]                   FLOAT (53)    NULL,
    [ENCNTR_ID]                    FLOAT (53)    NULL,
    [UPDT_CNT]                     FLOAT (53)    NULL,
    [UPDT_DT_TM]                   DATETIME      NULL,
    [UPDT_ID]                      FLOAT (53)    NULL,
    [UPDT_TASK]                    FLOAT (53)    NULL,
    [UPDT_APPLCTX]                 FLOAT (53)    NULL,
    [PRIORITY_SEQ]                 FLOAT (53)    NULL,
    [PROC_START_DT_TM]             DATETIME      NULL,
    [SCHED_XRAY_TECH_IND]          FLOAT (53)    NULL,
    [SCHED_XRAY_IND]               FLOAT (53)    NULL,
    [CONCURRENT_IND]               FLOAT (53)    NULL,
    [SCHED_DUR]                    FLOAT (53)    NULL,
    [SCHED_PRIMARY_IND]            FLOAT (53)    NULL,
    [SCHED_SURGE_AREA_CD]          FLOAT (53)    NULL,
    [SCHED_PRIORITY_CD]            FLOAT (53)    NULL,
    [SCHED_ANESTH_TYPE_CD]         FLOAT (53)    NULL,
    [SCHED_PRIMARY_SURGEON_ID]     FLOAT (53)    NULL,
    [NCEPOD_CD]                    FLOAT (53)    NULL,
    [SCHED_SURGICAL_MOD3_CD]       FLOAT (53)    NULL,
    [SCHED_SURGICAL_MOD2_CD]       FLOAT (53)    NULL,
    [SCHED_SURGICAL_MOD1_CD]       FLOAT (53)    NULL,
    [SCHED_SURGICAL_ORDER_COMMENT] VARCHAR (255) NULL,
    [PROC_TEXT]                    VARCHAR (255) NULL,
    [LAST_UTC_TS]                  VARCHAR (75)  NULL,
    [INST_ID]                      FLOAT (53)    NULL,
    [RowCreated]                   DATETIME2 (3) NOT NULL,
    [RowModified]                  DATETIME2 (3) NULL,
    [RowDeleted]                   DATETIME2 (0) NULL,
    [RowAltered]                   DATETIME2 (0) NOT NULL, 
    CONSTRAINT [PK_ENCNTR_PROCEDURE] PRIMARY KEY ([ENCNTR_PROCEDURE_ID])
);

