CREATE TABLE [stage].[ENCOUNTER] (
    [ENCNTR_ID]                    FLOAT (53)    NULL,
    [PERSON_ID]                    FLOAT (53)    NULL,
    [UPDT_CNT]                     FLOAT (53)    NULL,
    [UPDT_DT_TM]                   DATETIME      NULL,
    [UPDT_ID]                      FLOAT (53)    NULL,
    [UPDT_TASK]                    FLOAT (53)    NULL,
    [UPDT_APPLCTX]                 FLOAT (53)    NULL,
    [ACTIVE_IND]                   FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]             FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]          DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID]       FLOAT (53)    NULL,
    [CREATE_DT_TM]                 DATETIME      NULL,
    [CREATE_PRSNL_ID]              FLOAT (53)    NULL,
    [BEG_EFFECTIVE_DT_TM]          DATETIME      NULL,
    [END_EFFECTIVE_DT_TM]          DATETIME      NULL,
    [ENCNTR_CLASS_CD]              FLOAT (53)    NULL,
    [ENCNTR_TYPE_CD]               FLOAT (53)    NULL,
    [ENCNTR_TYPE_CLASS_CD]         FLOAT (53)    NULL,
    [ENCNTR_STATUS_CD]             FLOAT (53)    NULL,
    [PRE_REG_DT_TM]                DATETIME      NULL,
    [PRE_REG_PRSNL_ID]             FLOAT (53)    NULL,
    [REG_DT_TM]                    DATETIME      NULL,
    [REG_PRSNL_ID]                 FLOAT (53)    NULL,
    [EST_ARRIVE_DT_TM]             DATETIME      NULL,
    [EST_DEPART_DT_TM]             DATETIME      NULL,
    [ARRIVE_DT_TM]                 DATETIME      NULL,
    [DEPART_DT_TM]                 DATETIME      NULL,
    [ADMIT_TYPE_CD]                FLOAT (53)    NULL,
    [ADMIT_SRC_CD]                 FLOAT (53)    NULL,
    [ADMIT_MODE_CD]                FLOAT (53)    NULL,
    [ADMIT_WITH_MEDICATION_CD]     FLOAT (53)    NULL,
    [REFERRING_COMMENT]            VARCHAR (100) NULL,
    [DISCH_DISPOSITION_CD]         FLOAT (53)    NULL,
    [DISCH_TO_LOCTN_CD]            FLOAT (53)    NULL,
    [PREADMIT_NBR]                 VARCHAR (100) NULL,
    [PREADMIT_TESTING_CD]          FLOAT (53)    NULL,
    [READMIT_CD]                   FLOAT (53)    NULL,
    [ACCOMMODATION_CD]             FLOAT (53)    NULL,
    [ACCOMMODATION_REQUEST_CD]     FLOAT (53)    NULL,
    [ALT_RESULT_DEST_CD]           FLOAT (53)    NULL,
    [AMBULATORY_COND_CD]           FLOAT (53)    NULL,
    [COURTESY_CD]                  FLOAT (53)    NULL,
    [DIET_TYPE_CD]                 FLOAT (53)    NULL,
    [ISOLATION_CD]                 FLOAT (53)    NULL,
    [MED_SERVICE_CD]               FLOAT (53)    NULL,
    [RESULT_DEST_CD]               FLOAT (53)    NULL,
    [CONFID_LEVEL_CD]              FLOAT (53)    NULL,
    [VIP_CD]                       FLOAT (53)    NULL,
    [NAME_LAST_KEY]                VARCHAR (200) NULL,
    [NAME_FIRST_KEY]               VARCHAR (200) NULL,
    [NAME_FULL_FORMATTED]          VARCHAR (200) NULL,
    [NAME_LAST]                    VARCHAR (200) NULL,
    [NAME_FIRST]                   VARCHAR (200) NULL,
    [NAME_PHONETIC]                VARCHAR (200) NULL,
    [SEX_CD]                       FLOAT (53)    NULL,
    [BIRTH_DT_CD]                  FLOAT (53)    NULL,
    [BIRTH_DT_TM]                  DATETIME      NULL,
    [SPECIES_CD]                   FLOAT (53)    NULL,
    [DATA_STATUS_CD]               FLOAT (53)    NULL,
    [DATA_STATUS_DT_TM]            DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]         FLOAT (53)    NULL,
    [CONTRIBUTOR_SYSTEM_CD]        FLOAT (53)    NULL,
    [LOCATION_CD]                  FLOAT (53)    NULL,
    [LOC_FACILITY_CD]              FLOAT (53)    NULL,
    [LOC_BUILDING_CD]              FLOAT (53)    NULL,
    [LOC_NURSE_UNIT_CD]            FLOAT (53)    NULL,
    [LOC_ROOM_CD]                  FLOAT (53)    NULL,
    [LOC_BED_CD]                   FLOAT (53)    NULL,
    [DISCH_DT_TM]                  DATETIME      NULL,
    [GUARANTOR_TYPE_CD]            FLOAT (53)    NULL,
    [LOC_TEMP_CD]                  FLOAT (53)    NULL,
    [ORGANIZATION_ID]              FLOAT (53)    NULL,
    [REASON_FOR_VISIT]             VARCHAR (255) NULL,
    [ENCNTR_FINANCIAL_ID]          FLOAT (53)    NULL,
    [NAME_FIRST_SYNONYM_ID]        FLOAT (53)    NULL,
    [FINANCIAL_CLASS_CD]           FLOAT (53)    NULL,
    [BBD_PROCEDURE_CD]             FLOAT (53)    NULL,
    [INFO_GIVEN_BY]                VARCHAR (100) NULL,
    [SAFEKEEPING_CD]               FLOAT (53)    NULL,
    [TRAUMA_CD]                    FLOAT (53)    NULL,
    [TRIAGE_CD]                    FLOAT (53)    NULL,
    [TRIAGE_DT_TM]                 DATETIME      NULL,
    [VISITOR_STATUS_CD]            FLOAT (53)    NULL,
    [VALUABLES_CD]                 FLOAT (53)    NULL,
    [SECURITY_ACCESS_CD]           FLOAT (53)    NULL,
    [REFER_FACILITY_CD]            FLOAT (53)    NULL,
    [TRAUMA_DT_TM]                 DATETIME      NULL,
    [ACCOMP_BY_CD]                 FLOAT (53)    NULL,
    [ACCOMMODATION_REASON_CD]      FLOAT (53)    NULL,
    [CHART_COMPLETE_DT_TM]         DATETIME      NULL,
    [ZERO_BALANCE_DT_TM]           DATETIME      NULL,
    [ARCHIVE_DT_TM_EST]            DATETIME      NULL,
    [ARCHIVE_DT_TM_ACT]            DATETIME      NULL,
    [PURGE_DT_TM_EST]              DATETIME      NULL,
    [PURGE_DT_TM_ACT]              DATETIME      NULL,
    [ENCNTR_COMPLETE_DT_TM]        DATETIME      NULL,
    [PA_CURRENT_STATUS_CD]         FLOAT (53)    NULL,
    [PA_CURRENT_STATUS_DT_TM]      DATETIME      NULL,
    [PARENT_RET_CRITERIA_ID]       FLOAT (53)    NULL,
    [SERVICE_CATEGORY_CD]          FLOAT (53)    NULL,
    [CONTRACT_STATUS_CD]           FLOAT (53)    NULL,
    [EST_LENGTH_OF_STAY]           FLOAT (53)    NULL,
    [ALT_LVL_CARE_CD]              FLOAT (53)    NULL,
    [ASSIGN_TO_LOC_DT_TM]          DATETIME      NULL,
    [PROGRAM_SERVICE_CD]           FLOAT (53)    NULL,
    [SPECIALTY_UNIT_CD]            FLOAT (53)    NULL,
    [MENTAL_HEALTH_DT_TM]          DATETIME      NULL,
    [MENTAL_HEALTH_CD]             FLOAT (53)    NULL,
    [DOC_RCVD_DT_TM]               DATETIME      NULL,
    [REFERRAL_RCVD_DT_TM]          DATETIME      NULL,
    [ALT_LVL_CARE_DT_TM]           DATETIME      NULL,
    [ALC_DECOMP_DT_TM]             DATETIME      NULL,
    [REGION_CD]                    FLOAT (53)    NULL,
    [SITTER_REQUIRED_CD]           FLOAT (53)    NULL,
    [ALC_REASON_CD]                FLOAT (53)    NULL,
    [PLACEMENT_AUTH_PRSNL_ID]      FLOAT (53)    NULL,
    [PATIENT_CLASSIFICATION_CD]    FLOAT (53)    NULL,
    [MENTAL_CATEGORY_CD]           FLOAT (53)    NULL,
    [PSYCHIATRIC_STATUS_CD]        FLOAT (53)    NULL,
    [INPATIENT_ADMIT_DT_TM]        DATETIME      NULL,
    [RESULT_ACCUMULATION_DT_TM]    DATETIME      NULL,
    [PREGNANCY_STATUS_CD]          FLOAT (53)    NULL,
    [INITIAL_CONTACT_DT_TM]        DATETIME      NULL,
    [ONSET_DT_TM]                  DATETIME      NULL,
    [LAST_MENSTRUAL_PERIOD_DT_TM]  DATETIME      NULL,
    [EXPECTED_DELIVERY_DT_TM]      DATETIME      NULL,
    [ABN_STATUS_CD]                FLOAT (53)    NULL,
    [LEVEL_OF_SERVICE_CD]          FLOAT (53)    NULL,
    [PLACE_OF_SVC_ADMIT_DT_TM]     DATETIME      NULL,
    [PLACE_OF_SVC_TYPE_CD]         FLOAT (53)    NULL,
    [PLACE_OF_SVC_ORG_ID]          FLOAT (53)    NULL,
    [LAST_UTC_TS]                  VARCHAR (75)  NULL,
    [EST_FINANCIAL_RESP_AMT]       FLOAT (53)    NULL,
    [REFERRAL_SOURCE_CD]           FLOAT (53)    NULL,
    [ADMIT_DECISION_DT_TM]         DATETIME      NULL,
    [ACCIDENT_RELATED_IND]         FLOAT (53)    NULL,
    [DISCH_PRSNL_ID]               FLOAT (53)    NULL,
    [PAYMENT_COLLECTION_STATUS_CD] FLOAT (53)    NULL,
    [ORDER_SOURCE_CD]              FLOAT (53)    NULL,
    [ADMIT_EARLY_IND]              FLOAT (53)    NULL,
    [TREATMENT_PHASE_CD]           FLOAT (53)    NULL,
    [KIOSK_QUEUE_NBR_TXT]          VARCHAR (50)  NULL,
    [KIOSK_QUEUE_NBR_DT_TM]        DATETIME      NULL,
    [CLU_SUBKEY1_FLAG]             FLOAT (53)    NULL,
    [REFER_TO_UNIT_STAFF_CD]       FLOAT (53)    NULL,
    [LODGER_CD]                    FLOAT (53)    NULL,
    [COMPLETE_REG_DT_TM]           DATETIME      NULL,
    [COMPLETE_REG_PRSNL_ID]        FLOAT (53)    NULL,
    [CLERGY_VISIT_CD]              FLOAT (53)    NULL,
    [CLIENT_ORGANIZATION_ID]       FLOAT (53)    NULL,
    [PERSON_PLAN_PROFILE_TYPE_CD]  FLOAT (53)    NULL,
    [MILITARY_SERVICE_RELATED_CD]  FLOAT (53)    NULL,
    [INCIDENT_CD]                  FLOAT (53)    NULL,
    [ED_REFERRAL_SOURCE_CD]        FLOAT (53)    NULL,
    [INST_ID]                      FLOAT (53)    NULL
);

