CREATE TABLE [stage].[ENCNTR_PLAN_RELTN] (
    [ENCNTR_PLAN_RELTN_ID]           FLOAT (53)    NULL,
    [ENCNTR_ID]                      FLOAT (53)    NULL,
    [PERSON_ID]                      FLOAT (53)    NULL,
    [PERSON_PLAN_RELTN_ID]           FLOAT (53)    NULL,
    [HEALTH_PLAN_ID]                 FLOAT (53)    NULL,
    [ORGANIZATION_ID]                FLOAT (53)    NULL,
    [PERSON_ORG_RELTN_ID]            FLOAT (53)    NULL,
    [CONTRIBUTOR_SYSTEM_CD]          FLOAT (53)    NULL,
    [UPDT_CNT]                       FLOAT (53)    NULL,
    [UPDT_DT_TM]                     DATETIME      NULL,
    [UPDT_ID]                        FLOAT (53)    NULL,
    [UPDT_TASK]                      FLOAT (53)    NULL,
    [UPDT_APPLCTX]                   FLOAT (53)    NULL,
    [ACTIVE_IND]                     FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]               FLOAT (53)    NULL,
    [ACTIVE_STATUS_PRSNL_ID]         FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]            DATETIME      NULL,
    [BEG_EFFECTIVE_DT_TM]            DATETIME      NULL,
    [DATA_STATUS_CD]                 FLOAT (53)    NULL,
    [DATA_STATUS_DT_TM]              DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]           FLOAT (53)    NULL,
    [END_EFFECTIVE_DT_TM]            DATETIME      NULL,
    [SUBSCRIBER_TYPE_CD]             FLOAT (53)    NULL,
    [ORIG_PRIORITY_SEQ]              FLOAT (53)    NULL,
    [PRIORITY_SEQ]                   FLOAT (53)    NULL,
    [MEMBER_NBR]                     VARCHAR (100) NULL,
    [SUBS_MEMBER_NBR]                VARCHAR (100) NULL,
    [INSUR_SOURCE_INFO_CD]           FLOAT (53)    NULL,
    [BALANCE_TYPE_CD]                FLOAT (53)    NULL,
    [DEDUCT_AMT]                     FLOAT (53)    NULL,
    [DEDUCT_MET_AMT]                 FLOAT (53)    NULL,
    [DEDUCT_MET_DT_TM]               DATETIME      NULL,
    [ASSIGN_BENEFITS_CD]             FLOAT (53)    NULL,
    [COORD_BENEFITS_CD]              FLOAT (53)    NULL,
    [PLAN_TYPE_CD]                   FLOAT (53)    NULL,
    [PLAN_CLASS_CD]                  FLOAT (53)    NULL,
    [HEALTH_CARD_PROVINCE]           VARCHAR (3)   NULL,
    [HEALTH_CARD_VER_CODE]           VARCHAR (3)   NULL,
    [HEALTH_CARD_NBR]                VARCHAR (100) NULL,
    [INSURED_CARD_NAME]              VARCHAR (100) NULL,
    [GROUP_NAME]                     VARCHAR (200) NULL,
    [GROUP_NBR]                      VARCHAR (100) NULL,
    [POLICY_NBR]                     VARCHAR (100) NULL,
    [SPONSOR_PERSON_ORG_RELTN_ID]    FLOAT (53)    NULL,
    [MILITARY_RANK_CD]               FLOAT (53)    NULL,
    [MILITARY_STATUS_CD]             FLOAT (53)    NULL,
    [MILITARY_SERVICE_CD]            FLOAT (53)    NULL,
    [MILITARY_BASE_LOCATION]         VARCHAR (100) NULL,
    [HEALTH_CARD_TYPE]               VARCHAR (32)  NULL,
    [HEALTH_CARD_ISSUE_DT_TM]        DATETIME      NULL,
    [HEALTH_CARD_EXPIRY_DT_TM]       DATETIME      NULL,
    [MEMBER_PERSON_CODE]             VARCHAR (100) NULL,
    [INS_CARD_COPIED_CD]             FLOAT (53)    NULL,
    [LIFE_RSV_DAYS]                  FLOAT (53)    NULL,
    [LIFE_RSV_REMAIN_DAYS]           FLOAT (53)    NULL,
    [LIFE_RSV_DAILY_DED_AMT]         FLOAT (53)    NULL,
    [LIFE_RSV_DAILY_DED_QUAL_CD]     FLOAT (53)    NULL,
    [CARD_ISSUE_NBR]                 FLOAT (53)    NULL,
    [CARD_CATEGORY_CD]               FLOAT (53)    NULL,
    [PROGRAM_STATUS_CD]              FLOAT (53)    NULL,
    [VERIFY_PRSNL_ID]                FLOAT (53)    NULL,
    [VERIFY_DT_TM]                   DATETIME      NULL,
    [VERIFY_STATUS_CD]               FLOAT (53)    NULL,
    [DENIAL_REASON_CD]               FLOAT (53)    NULL,
    [COVERAGE_COMMENTS_LONG_TEXT_ID] FLOAT (53)    NULL,
    [SIGNATURE_ON_FILE_CD]           FLOAT (53)    NULL,
    [PRICING_AGENCY_CD]              FLOAT (53)    NULL,
    [RX_PLAN_COB_SEQ]                FLOAT (53)    NULL,
    [SIGNATURE_SOURCE_CD]            FLOAT (53)    NULL,
    [ACCEPT_ASSIGNMENT_CD]           FLOAT (53)    NULL,
    [SIGNATURE_DT_TM]                DATETIME      NULL,
    [INSURED_CARD_NAME_MIDDLE]       VARCHAR (100) NULL,
    [INSURED_CARD_NAME_LAST]         VARCHAR (100) NULL,
    [INSURED_CARD_NAME_SUFFIX]       VARCHAR (100) NULL,
    [INSURED_CARD_NAME_FIRST]        VARCHAR (100) NULL,
    [PROP_CASUALTY_CLAIM_NBR_TXT]    VARCHAR (100) NULL,
    [VERIFY_SOURCE_CD]               FLOAT (53)    NULL,
    [LAST_UTC_TS]                    VARCHAR (75)  NULL,
    [NOTIFY_SOURCE_CD]               FLOAT (53)    NULL,
    [RESUBMIT_278N_CD]               FLOAT (53)    NULL,
    [ALT_MEMBER_NBR]                 VARCHAR (100) NULL,
    [EXT_PAYER_NAME]                 VARCHAR (100) NULL,
    [EXT_PAYER_IDENT]                VARCHAR (100) NULL,
    [NOTIFY_DT_TM]                   DATETIME      NULL,
    [NOTIFY_PRSNL_ID]                FLOAT (53)    NULL,
    [AUTH_REQUIRED_CD]               FLOAT (53)    NULL,
    [GENERIC_HEALTH_PLAN_NAME]       VARCHAR (100) NULL,
    [INS_OFFICE_ORG_ID]              FLOAT (53)    NULL,
    [BENEFIT_VERIFY_DT_TM]           DATETIME      NULL,
    [INST_ID]                        FLOAT (53)    NULL
);

