CREATE TABLE [stage].[PERSON_PLAN_RELTN] (
    [PERSON_PLAN_RELTN_ID]           FLOAT (53)    NULL,
    [HEALTH_PLAN_ID]                 FLOAT (53)    NULL,
    [PERSON_ID]                      FLOAT (53)    NULL,
    [PERSON_PLAN_R_CD]               FLOAT (53)    NULL,
    [PERSON_ORG_RELTN_ID]            FLOAT (53)    NULL,
    [ORGANIZATION_ID]                FLOAT (53)    NULL,
    [UPDT_CNT]                       FLOAT (53)    NULL,
    [UPDT_DT_TM]                     DATETIME      NULL,
    [UPDT_ID]                        FLOAT (53)    NULL,
    [UPDT_TASK]                      FLOAT (53)    NULL,
    [UPDT_APPLCTX]                   FLOAT (53)    NULL,
    [ACTIVE_IND]                     FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]               FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]            DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID]         FLOAT (53)    NULL,
    [BEG_EFFECTIVE_DT_TM]            DATETIME      NULL,
    [END_EFFECTIVE_DT_TM]            DATETIME      NULL,
    [CONTRIBUTOR_SYSTEM_CD]          FLOAT (53)    NULL,
    [PRIORITY_SEQ]                   FLOAT (53)    NULL,
    [MEMBER_NBR]                     VARCHAR (100) NULL,
    [SIGNATURE_ON_FILE_CD]           FLOAT (53)    NULL,
    [BALANCE_TYPE_CD]                FLOAT (53)    NULL,
    [DEDUCT_AMT]                     FLOAT (53)    NULL,
    [DEDUCT_MET_AMT]                 FLOAT (53)    NULL,
    [DEDUCT_MET_DT_TM]               DATETIME      NULL,
    [COVERAGE_TYPE_CD]               FLOAT (53)    NULL,
    [MAX_OUT_PCKT_AMT]               FLOAT (53)    NULL,
    [MAX_OUT_PCKT_DT_TM]             DATETIME      NULL,
    [FAM_DEDUCT_MET_AMT]             FLOAT (53)    NULL,
    [FAM_DEDUCT_MET_DT_TM]           DATETIME      NULL,
    [VERIFY_STATUS_CD]               FLOAT (53)    NULL,
    [VERIFY_DT_TM]                   DATETIME      NULL,
    [VERIFY_PRSNL_ID]                FLOAT (53)    NULL,
    [PLAN_TYPE_CD]                   FLOAT (53)    NULL,
    [PLAN_CLASS_CD]                  FLOAT (53)    NULL,
    [INSURED_CARD_NAME]              VARCHAR (100) NULL,
    [GROUP_NAME]                     VARCHAR (200) NULL,
    [GROUP_NBR]                      VARCHAR (100) NULL,
    [POLICY_NBR]                     VARCHAR (100) NULL,
    [SPONSOR_PERSON_ORG_RELTN_ID]    FLOAT (53)    NULL,
    [SUBSCRIBER_PERSON_ID]           FLOAT (53)    NULL,
    [MEMBER_PERSON_CODE]             VARCHAR (100) NULL,
    [LIFE_RSV_DAYS]                  FLOAT (53)    NULL,
    [LIFE_RSV_REMAIN_DAYS]           FLOAT (53)    NULL,
    [LIFE_RSV_DAILY_DED_AMT]         FLOAT (53)    NULL,
    [LIFE_RSV_DAILY_DED_QUAL_CD]     FLOAT (53)    NULL,
    [CARD_ISSUE_NBR]                 FLOAT (53)    NULL,
    [CARD_CATEGORY_CD]               FLOAT (53)    NULL,
    [PROGRAM_STATUS_CD]              FLOAT (53)    NULL,
    [DENIAL_REASON_CD]               FLOAT (53)    NULL,
    [COVERAGE_COMMENTS_LONG_TEXT_ID] FLOAT (53)    NULL,
    [CONTRACT_CODE]                  VARCHAR (100) NULL,
    [INSURED_CARD_NAME_FIRST]        VARCHAR (100) NULL,
    [INSURED_CARD_NAME_MIDDLE]       VARCHAR (100) NULL,
    [INSURED_CARD_NAME_SUFFIX]       VARCHAR (100) NULL,
    [INSURED_CARD_NAME_LAST]         VARCHAR (100) NULL,
    [VERIFY_SOURCE_CD]               FLOAT (53)    NULL,
    [LAST_UTC_TS]                    VARCHAR (75)  NULL,
    [EXT_PAYER_NAME]                 VARCHAR (100) NULL,
    [EXT_PAYER_IDENT]                VARCHAR (100) NULL,
    [ALT_MEMBER_NBR]                 VARCHAR (100) NULL,
    [GENERIC_HEALTH_PLAN_NAME]       VARCHAR (100) NULL,
    [INS_OFFICE_ORG_ID]              FLOAT (53)    NULL,
    [INST_ID]                        FLOAT (53)    NULL
);

