CREATE TABLE [stage].[PERSON] (
    [PERSON_ID]                  FLOAT (53)    NULL,
    [UPDT_CNT]                   FLOAT (53)    NULL,
    [UPDT_DT_TM]                 DATETIME      NULL,
    [UPDT_ID]                    FLOAT (53)    NULL,
    [UPDT_TASK]                  FLOAT (53)    NULL,
    [UPDT_APPLCTX]               FLOAT (53)    NULL,
    [ACTIVE_IND]                 FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]           FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]        DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID]     FLOAT (53)    NULL,
    [CREATE_DT_TM]               DATETIME      NULL,
    [CREATE_PRSNL_ID]            FLOAT (53)    NULL,
    [BEG_EFFECTIVE_DT_TM]        DATETIME      NULL,
    [END_EFFECTIVE_DT_TM]        DATETIME      NULL,
    [PERSON_TYPE_CD]             FLOAT (53)    NULL,
    [NAME_LAST_KEY]              VARCHAR (100) NULL,
    [NAME_FIRST_KEY]             VARCHAR (100) NULL,
    [NAME_FULL_FORMATTED]        VARCHAR (100) NULL,
    [AUTOPSY_CD]                 FLOAT (53)    NULL,
    [BIRTH_DT_CD]                FLOAT (53)    NULL,
    [BIRTH_DT_TM]                DATETIME      NULL,
    [CONCEPTION_DT_TM]           DATETIME      NULL,
    [CAUSE_OF_DEATH]             VARCHAR (100) NULL,
    [DECEASED_CD]                FLOAT (53)    NULL,
    [DECEASED_DT_TM]             DATETIME      NULL,
    [ETHNIC_GRP_CD]              FLOAT (53)    NULL,
    [LANGUAGE_CD]                FLOAT (53)    NULL,
    [MARITAL_TYPE_CD]            FLOAT (53)    NULL,
    [PURGE_OPTION_CD]            FLOAT (53)    NULL,
    [RACE_CD]                    FLOAT (53)    NULL,
    [RELIGION_CD]                FLOAT (53)    NULL,
    [SEX_CD]                     FLOAT (53)    NULL,
    [SEX_AGE_CHANGE_IND]         FLOAT (53)    NULL,
    [DATA_STATUS_CD]             FLOAT (53)    NULL,
    [DATA_STATUS_DT_TM]          DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]       FLOAT (53)    NULL,
    [CONTRIBUTOR_SYSTEM_CD]      FLOAT (53)    NULL,
    [LANGUAGE_DIALECT_CD]        FLOAT (53)    NULL,
    [NAME_LAST]                  VARCHAR (200) NULL,
    [NAME_FIRST]                 VARCHAR (200) NULL,
    [NAME_PHONETIC]              VARCHAR (8)   NULL,
    [LAST_ENCNTR_DT_TM]          DATETIME      NULL,
    [SPECIES_CD]                 FLOAT (53)    NULL,
    [CONFID_LEVEL_CD]            FLOAT (53)    NULL,
    [VIP_CD]                     FLOAT (53)    NULL,
    [NAME_FIRST_SYNONYM_ID]      FLOAT (53)    NULL,
    [CITIZENSHIP_CD]             FLOAT (53)    NULL,
    [VET_MILITARY_STATUS_CD]     FLOAT (53)    NULL,
    [MOTHER_MAIDEN_NAME]         VARCHAR (100) NULL,
    [NATIONALITY_CD]             FLOAT (53)    NULL,
    [FT_ENTITY_NAME]             VARCHAR (32)  NULL,
    [FT_ENTITY_ID]               FLOAT (53)    NULL,
    [NAME_MIDDLE_KEY]            VARCHAR (100) NULL,
    [NAME_MIDDLE]                VARCHAR (200) NULL,
    [NAME_FIRST_PHONETIC]        VARCHAR (8)   NULL,
    [NAME_LAST_PHONETIC]         VARCHAR (8)   NULL,
    [NAME_LAST_KEY_NLS]          VARCHAR (202) NULL,
    [NAME_FIRST_KEY_NLS]         VARCHAR (202) NULL,
    [NAME_MIDDLE_KEY_NLS]        VARCHAR (202) NULL,
    [MILITARY_RANK_CD]           FLOAT (53)    NULL,
    [MILITARY_BASE_LOCATION]     VARCHAR (100) NULL,
    [MILITARY_SERVICE_CD]        FLOAT (53)    NULL,
    [DECEASED_SOURCE_CD]         FLOAT (53)    NULL,
    [CAUSE_OF_DEATH_CD]          FLOAT (53)    NULL,
    [BIRTH_TZ]                   FLOAT (53)    NULL,
    [BIRTH_PREC_FLAG]            FLOAT (53)    NULL,
    [ABS_BIRTH_DT_TM]            DATETIME      NULL,
    [ARCHIVE_ENV_ID]             FLOAT (53)    NULL,
    [ARCHIVE_STATUS_CD]          FLOAT (53)    NULL,
    [LAST_ACCESSED_DT_TM]        DATETIME      NULL,
    [ARCHIVE_STATUS_DT_TM]       DATETIME      NULL,
    [NEXT_RESTORE_DT_TM]         DATETIME      NULL,
    [AGE_AT_DEATH]               FLOAT (53)    NULL,
    [AGE_AT_DEATH_UNIT_CD]       FLOAT (53)    NULL,
    [AGE_AT_DEATH_PREC_MOD_FLAG] FLOAT (53)    NULL,
    [DECEASED_TZ]                FLOAT (53)    NULL,
    [DECEASED_DT_TM_PREC_FLAG]   FLOAT (53)    NULL,
    [DECEASED_ID_METHOD_CD]      FLOAT (53)    NULL,
    [LOGICAL_DOMAIN_ID]          FLOAT (53)    NULL,
    [NAME_LAST_KEY_A_NLS]        VARCHAR (400) NULL,
    [NAME_FIRST_KEY_A_NLS]       VARCHAR (400) NULL,
    [NAME_MIDDLE_KEY_A_NLS]      VARCHAR (400) NULL,
    [PERSON_STATUS_CD]           FLOAT (53)    NULL,
    [LAST_UTC_TS]                VARCHAR (75)  NULL,
    [RESIDENT_CD]                FLOAT (53)    NULL,
    [EMANCIPATION_DT_TM]         DATETIME      NULL,
    [INST_ID]                    FLOAT (53)    NULL
);

