

CREATE TABLE [dbo].[Phone] (
    [PHONE_ID]               FLOAT (53)    NULL,
    [PARENT_ENTITY_NAME]     VARCHAR (32)  NULL,
    [PARENT_ENTITY_ID]       FLOAT (53)    NULL,
    [PHONE_TYPE_CD]          FLOAT (53)    NULL,
    [UPDT_CNT]               FLOAT (53)    NULL,
    [UPDT_DT_TM]             DATETIME      NULL,
    [UPDT_ID]                FLOAT (53)    NULL,
    [UPDT_TASK]              FLOAT (53)    NULL,
    [UPDT_APPLCTX]           FLOAT (53)    NULL,
    [ACTIVE_IND]             FLOAT (53)    NULL,
    [ACTIVE_STATUS_CD]       FLOAT (53)    NULL,
    [ACTIVE_STATUS_DT_TM]    DATETIME      NULL,
    [ACTIVE_STATUS_PRSNL_ID] FLOAT (53)    NULL,
    [PHONE_FORMAT_CD]        FLOAT (53)    NULL,
    [PHONE_NUM]              VARCHAR (100) NULL,
    [PHONE_TYPE_SEQ]         FLOAT (53)    NULL,
    [DESCRIPTION]            VARCHAR (100) NULL,
    [CONTACT]                VARCHAR (100) NULL,
    [CALL_INSTRUCTION]       VARCHAR (300) NULL,
    [MODEM_CAPABILITY_CD]    FLOAT (53)    NULL,
    [EXTENSION]              VARCHAR (100) NULL,
    [PAGING_CODE]            VARCHAR (100) NULL,
    [BEG_EFFECTIVE_DT_TM]    DATETIME      NULL,
    [END_EFFECTIVE_DT_TM]    DATETIME      NULL,
    [DATA_STATUS_CD]         FLOAT (53)    NULL,
    [DATA_STATUS_DT_TM]      DATETIME      NULL,
    [DATA_STATUS_PRSNL_ID]   FLOAT (53)    NULL,
    [BEG_EFFECTIVE_MM_DD]    FLOAT (53)    NULL,
    [END_EFFECTIVE_MM_DD]    FLOAT (53)    NULL,
    [CONTRIBUTOR_SYSTEM_CD]  FLOAT (53)    NULL,
    [OPERATION_HOURS]        VARCHAR (255) NULL,
    [LONG_TEXT_ID]           FLOAT (53)    NULL,
    [CONTACT_METHOD_CD]      FLOAT (53)    NULL,
    [SOURCE_IDENTIFIER]      VARCHAR (255) NULL,
    [PHONE_NUM_KEY]          VARCHAR (100) NULL,
    [PHONE_NUM_KEY_NLS]      VARCHAR (202) NULL,
    [PHONE_NUM_KEY_A_NLS]    VARCHAR (400) NULL,
    [LAST_UTC_TS]            VARCHAR (75)  NULL,
    [TEXTING_PERMISSION_CD]  FLOAT (53)    NULL,
    [INST_ID]                FLOAT (53)    NULL
);


